<a href="https://colab.research.google.com/github/pkro/pytorch_for_deep_learning/blob/main/00_pytorch_fundamentals_exercises_done.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
t_rand1 = torch.rand([7,7])
t_rand1

tensor([[0.2273, 0.9973, 0.1538, 0.7387, 0.6966, 0.4687, 0.3684],
        [0.4787, 0.5831, 0.0600, 0.4025, 0.2315, 0.8016, 0.8797],
        [0.3428, 0.8420, 0.6381, 0.3320, 0.6740, 0.6948, 0.0353],
        [0.0015, 0.1687, 0.3066, 0.3123, 0.6061, 0.5637, 0.6874],
        [0.6847, 0.6770, 0.7906, 0.1364, 0.6156, 0.1918, 0.7726],
        [0.9652, 0.0638, 0.4091, 0.1357, 0.3043, 0.9744, 0.5119],
        [0.6309, 0.3815, 0.1236, 0.4124, 0.7083, 0.1268, 0.5089]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
t_rand2 = torch.rand(1,7)

# Perform matrix multiplication

torch.matmul(t_rand1, t_rand2.T)

tensor([[1.8340],
        [1.8761],
        [1.8143],
        [1.2654],
        [1.8983],
        [1.5193],
        [1.1146]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(7,7)
t2 = torch.rand(1,7)

# Matrix multiply tensors
torch.mm(t1, t2.T), torch.mm(t1, t2.T).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(0) #  or torch.cuda.manual_seed_all(0) if multiple GPUs


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.cuda.manual_seed(1234)
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
device = 'cuda' if torch.cuda.is_available else 'cpu'

# Create two random tensors on GPU
tcpu1 = torch.rand([2,3])
tcpu2 = torch.rand([2,3])

# to create directly on gpu:
# tgpu1 = torch.rand([2,3], device='cuda')
# tgpu2 = torch.rand([2,3], device='cuda')

# send to gpu
tgpu1 = tcpu1.to(device)
tgpu2 = tcpu2.to(device)

tgpu1, tgpu2


True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
res = torch.mm(tgpu1, tgpu2.T)
res

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(res.max())
# Find min
print(res.min())


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
# Find arg min

res.argmax(), res.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t1 = torch.rand([1,1,1,10])
print(t1)
print(t1.shape)

# Remove single dimensions
t1_squeezed = t1.squeeze();
print(t1_squeezed)
print(t1_squeezed.shape)
# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
